### ISSUE TITLE
tsserver not restarting after switching from `jose-elias-alvarez/typescript.nvim` to `pmizio/typescript-tools.nvim`

### ISSUE THREAD

**Issue by ls-devs** [hinell/lsp-timeout.nvim#12]
### Summary

**_EDIT_** : _After some investigations `tsserver` is restarted, but the LSP `typescript-tools` is not._
**_EDIT 2_** _It seems that `lua_ls` doesn't restart too. Can it be related to the fact that it is handled by `lsp-zero` ? Or by the latest update of `lsp-timeout`?_

Before switching from `jose-elias-alvarez/typescript.nvim` to `pmizio/typescript-tools.nvim` tsserver was restarting without any problems. Now it wont restart.

If it can help, here's `typescript-tools` config : 
```lua
local M = {}

M.config = function()
  local lsp_zero = require("lsp-zero")
  lsp_zero.extend_lspconfig()
  require("typescript-tools").setup({
    settings = {
      tsserver_file_preferences = {
        includeInlayParameterNameHints = "all",
        includeCompletionsForModuleExports = true,
        includeInlayParameterNameHintsWhenArgumentMatchesName = true,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayVariableTypeHints = true,
        includeInlayVariableTypeHintsWhenTypeMatchesName = true,
        includeInlayPropertyDeclarationTypeHints = true,
        includeInlayFunctionLikeReturnTypeHints = true,
        includeInlayEnumMemberValueHints = true,
      },
      tsserver_format_options = {
        allowIncompleteCompletions = false,
        allowRenameOfImportPath = true,
      },
      separate_diagnostic_server = true,
      publish_diagnostic_on = "insert_leave",
      expose_as_code_action = {},
      tsserver_max_memory = "auto",
      tsserver_locale = "fr",
      complete_function_calls = true,
      include_completions_with_insert_text = true,
      code_lens = "all",
      disable_member_code_lens = true,
    },
  })
end

return M
```

### Steps to reproduce

I don't have any steps to reproduce the issue, all I can give you is my neovim configuration if you want to try.
You can find it here : [ls-devs/nvim](https://github.com/ls-devs/nvim)

### Versions

NVIM v0.10.0-dev-1413+g684e93054-dirty
Build type: RelWithDebInfo
LuaJIT 2.1.1697887905

**Comment by ls-devs** [comment]
> @ls-devs Have you updated to `v1.1.0`?

@hinell Yes, of course.

**Comment by hinell** [comment]
https://github.com/hinell/lsp-timeout.nvim/assets/8136158/3ac7ab95-361d-4a35-b57b-0910af42da9f


I've tried to run `tsx` project. It works fine. 
* `nvim-lspconfig`: https://github.com/neovim/nvim-lspconfig/commit/6428fcab6f3c09e934bc016c329806314384a41e
* `pmizio/typescript-tools.nvim/`: https://github.com/pmizio/typescript-tools.nvim/commit/102ba313f87e1f9f9864f681dd7779cac8f6d3ea

Did you call `lspconfig["typescript-tools"].setup()`? 
Did you replace `lspconfig.tsserver.setup` with the following?:
```myfile/xyz.diff
-	lspconfig.tsserver.setup({ on_attach = on_attach })
+	require("typescript-tools").setup({})
+	lspconfig["typescript-tools"].setup({
+ 		-- ... your config
+	})
```

What does `:set ft?` reports on typescript files in your project?
I would suggest to specify more filetypes, so `tsx` files are hooked up by `lspconfig`.

```lsp/init.lua
-- Put this into plugin spec `config = function()` body:
require("typescript-tools").setup({})
lspconfig["typescript-tools"].setup({
	on_attach = on_attach,
	filetypes = {
		"javascript",
		"js",
		"jsx",
		"ts",
		"tsx",
		"typescript",
		"javascriptreact",
		"javascript.jsx",
		"typescript",
		"typescriptreact",
		"typescript.tsx",
	}

})
```

**Comment by ls-devs** [comment]
I can confirm it's working with the configuration you give me.
I forgot to add 
```lua
  require("lspconfig")["typescript-tools"].setup({
    filetypes = {
      "javascript",
      "js",
      "jsx",
      "ts",
      "tsx",
      "typescript",
      "javascriptreact",
      "javascript.jsx",
      "typescript",
      "typescriptreact",
      "typescript.tsx",
    },
  })
``` 
Couldn't find any mention of setting up `typescript-tools` with lspconfig, but found that we must disable tsserver.
Sorry for bothering with this issue since there's nothing to do with `lsp-timeout` here .

_Btw, appreciate your work and the changes you made about the focusable windows._

**Comment by hinell** [comment]
Close the issue if it's restarting LSPs as expected.

> Couldn't find any mention of setting up typescript-tools

Have you filled a bug report out there? It's a subtle omission from the readme ...

> Btw, appreciate your work

Took me entire day to upgrade it. There should be zero requirements for efforts to maintain this plugin. So less config is more.

**Comment by hinell** [comment]
Reflected in docs: https://github.com/hinell/lsp-timeout.nvim/commit/f3294c0fc2590dd019eca4a9c4466be42bce82e6 
Close this issue if it's restarting LSPs as expected.

> Couldn't find any mention of setting up typescript-tools

Fill a bug report out there.

> Btw, appreciate your work

Took me entire day to upgrade it. There should be zero requirements for efforts to maintain this plugin. So less config is more.
