### ISSUE TITLE
1.2.0 Error when neovim loses focus

### ISSUE THREAD

**Issue by Zeioth** [hinell/lsp-timeout.nvim#15]
### I've read [TROUBLESHOOTING](../blob/main/doc/index.md#TROUBLESHOOTING) instructions

- [X] Yes

### Summary

There seem to be a bug when the current neovim screen loses focus.
![screenshot_2023-10-29_20-35-20_742103937](https://github.com/hinell/lsp-timeout.nvim/assets/3357792/c11e06a5-5c5e-4427-bc07-9d1f58486feb)

## Config
```lua
  {
    "hinell/lsp-timeout.nvim",
    dependencies={ "neovim/nvim-lspconfig" },
    event = "User BaseFile",
    init = function()
      vim.g["lsp-timeout-config"] = {
        stopTimeout = 1000,        -- Stop unused lsp servers after 1s (for testing).
        startTimeout = 2000,             -- Force server restart if nvim can't in 2s.
        silent = true,                   -- Notifications disabled
        filetypes = {                    -- Exclude servers that miss behave on LSP stop/start.
          ignore = { 'markdown', 'java' }
        },
      }
    end
  },
```

## More info
I've tested with a few languages with the same result.

### Steps to reproduce

1. Use my config
2. Open any file that has an active lsp client.
3. move the mouse outside of neovim.

(it seems to be unrelated with the new option filetypes.)

### Versions

NVIM v0.10.0-dev-1418+g15983cf2c6
Build type: RelWithDebInfo
LuaJIT 2.1.1697887905
Run "nvim -V1 -v" for more info

### Specify operating system/environment

Archlinux

**Comment by hinell** [comment]
@Zeioth Thanks for speedy test. Please re-updated.

**Comment by hinell** [comment]
@Zeioth Thanks for a speedy test! Please re-update: 
```sh
cd ~/.local/share/nvim/lazy/lsp-timeout.nvim
git pull origin -f latest main
```

**Comment by Zeioth** [comment]
Ok now it works as usual. But with the next bugs:

* The new option `filetypes` is not actually ignoring the language. It kills it even if on the list.
```lua
        filetypes = {                    -- Exclude servers that miss behave on LSP stop/start.
          ignore = { 'markdown', 'java' }
        },
```
* On lua, it stop all except `lua_ls` for some reason

(pre-kill)
![screenshot_2023-10-29_21-02-37_179577479](https://github.com/hinell/lsp-timeout.nvim/assets/3357792/a20f3de1-b206-490f-8ce1-7752cc3a7e09)

(post-kill)
![screenshot_2023-10-29_21-01-43_316140182](https://github.com/hinell/lsp-timeout.nvim/assets/3357792/1607b75d-2a79-4d83-b0a6-fa88d58cd7df)

**Comment by hinell** [comment]
@Zeioth Add `lua` files to the config first.  ¯\_(ツ)_/¯.

**Comment by hinell** [comment]
@Zeioth Add `lua` files to the config first.  ¯\_(ツ)_/¯.  Please, close if fixed.

**Comment by Zeioth** [comment]
No, doesn't fix it. Answer not related with my report.

> @Zeioth Add `lua` files to the config first. ¯_(ツ)_/¯. Please, close if fixed.
> 
> ```diff
> filetypes = {
> -  ignore = { 'markdown', 'java' }
> +  ignore = { 'markdown', 'java', 'lua' }
> },
> ```

**Comment by hinell** [comment]
@Zeioth If I add `lua` to ignored list - `lsp-timeout` ignores user events in buffers with specified filetype. It will NOT try to start/stop any LSP clients or anything. It works for me at in both `tsx` and `lua` files.

**Comment by Zeioth** [comment]
After reinstalling the plugin, all works fine with my previous config. Closing.

Also, I've been reading the code and I would suggest to simplify it where possible in order to make it easier to maintain. And applying lua naming conventions like_this instead of camelCase.
