### ISSUE TITLE
Add ability to disable neovim on startup

### ISSUE THREAD

**Issue by dylan-chong** [hinell/lsp-timeout.nvim#21]
idea is using tmux, i want to restore many neovim sessions without triggering lsp.

could add option to disable lsp at startup until the user-has-come-back trigger triggers

**Comment by dylan-chong** [comment]
dude github deleted my entire description

**Comment by hinell** [comment]
You can use `LspStop` for that. It's provided by [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig).

**Comment by dylan-chong** [comment]
very curious, why does this plugin not use LspStop/LspStart?

**Comment by hinell** [comment]
@dylan-chong Because it manages both LspConfig-configured LSP clients and non-LspConfig ones.

**Comment by hinell** [comment]
@dylan-chong Because lsp-timeout manages both LspConfig-configured LSP clients and non-LspConfig ones.

**Comment by hinell** [comment]
If you want to disable LSP autostart upon launching a neovim instance, you can use a dedicated option for the lsp-config:
* https://github.com/neovim/nvim-lspconfig/pull/721
