### ISSUE TITLE
Does not work with `zbirenbaum/copilot.lua`

### ISSUE THREAD

**Issue by serhez** [hinell/lsp-timeout.nvim#22]
### I've read TROUBLESHOOTING instructions

- [x] Yes

### Summary

This plugin works fantastically well with every LSP server, but it seems to mess with Copilot when timing out all servers. When restarting, Copilot does not work again and querying its status simply outputs "Offline". Attempting to manually re-trigger Copilot (e.g., `Copilot! attach`) also outputs "Offline" and does not restart Copilot. I need to quit nvim and launch it again for Copilot to work. Any idea why this happens? Is there any way to also restart Copilot?

### Steps to reproduce

Use this plugin along with `zbirenbaum/copilot.lua`, wait for this plugin to timeout the servers and then attempt to use Copilot again.

`zbirenbaum/copilot.lua` config:
```lua
require("copilot").setup({
  panel = {
    enabled = true,
    auto_refresh = true,
    keymap = {
      jump_prev = "[[",
      jump_next = "]]",
      accept = "<CR>",
      refresh = "R",
      open = "<M-c>",
    },
    layout = {
      position = "right",
      ratio = 0.3,
    },
  },
  suggestion = {
    enabled = true,
    auto_trigger = true,
    keymap = {
      accept = "<M-l>",
      next = "<M-]>",
      prev = "<M-[>",
      dismiss = "<M-h>",
    },
  },
  filetypes = {
    yaml = true,
    markdown = true,
    help = false,
    gitcommit = true,
    gitrebase = true,
    hgcommit = true,
    svn = true,
    cvs = true,
    ["."] = false,
  },
  server_opts_overrides = {
    autostart = true,
  },
})
```

This plugin's config is the default one.

### Versions

nvim v0.10, latest versions of `zbirenbaum/copilot.lua` and this plugin.

### Specify operating system/environment

MacOS

**Comment by hinell** [comment]
1. Try to run `Copilot enable` 
2. Then copy & paste what the `Copilot status` outputs over here

**Comment by serhez** [comment]
The output of `Copilot enable` is `[Copilot] Online`. The output of `Copilot status` is `[Copilot] Enabled for python`. That looks promising, however I still don't get any suggestions after the restart.

EDIT: it seems the suggestions are not working for the buffer that was open, but if I open another buffer the suggestions work there.

**Comment by hinell** [comment]
@serhez You can run `:e` in the nvim commandline to re-open the current buffer file.

It turns out the `zbirenbaum/copilot.lua` uses unusual startup sequence unlike many others LSPs so my plugin won't work smoothly with that one.

**Comment by serhez** [comment]
Got it. Thanks for having a look! @hinell

**Comment by hinell** [comment]
@serhez Btw, after running `Copilot enable` and might also want to `attach` it to the current buffer.
