### ISSUE TITLE
switching buffers on restart makes the LSP attach to the wrong buffer

### ISSUE THREAD

**Issue by dylan-chong** [hinell/lsp-timeout.nvim#23]
### I've read TROUBLESHOOTING instructions

- [X] Yes

### Summary

![image](https://github.com/hinell/lsp-timeout.nvim/assets/17482349/c2c44751-ee95-4b43-8a8a-529444335955)

see lua and vim lsps are attached to the lua file buffer according to statusline

### Steps to reproduce

      vim.g.lspTimeoutConfig = {
        startTimeout = 1000 * 0.1,
        stopTimeout = 1000 * 2,
      }

1. open file a
2. open file b in another tab
3. defocus terminal
4. wait for timeout
5. focus terminal and switch to file a
6. lsp for language a and b will be active for buffer a and file b will show Lsp inactive status in statusline. file b may even have no lsps inactive 

probably some race condition with picking the current buffer after a time delay (after which the user has switched buffers)

### Versions

NVIM v0.11.0-dev-302+gbe999e6a0
plugin 6325906730330105a9adc41d0ceb8499b3072e2b

### Specify operating system/environment

Windows WSL

**Comment by hinell** [comment]
What lsp-s are involvted? 

Have to dig it up later, when have more time on hands. I'm currently busy with fixing my old laptop...

**Comment by hinell** [comment]
What lsp-s clients are involved? 

Have to dig it up later, when have more time on hands. I'm currently a bit busy with fixing my old laptop...

**Comment by hinell** [comment]
What lsp clients are involved?

Have to dig it up later, when I have more time on hands. Currently I'm a bit busy with fixing my old laptop...

**Comment by dylan-chong** [comment]
hey, cheers for the quick response. the dont think the lsp matters but in the example i have lua_ls/vimls. i can replicate with jsonls/tsserver too.

**Comment by dylan-chong** [comment]
i wonder if this line needs to pass the opts `{ bufnr: auEvent.buf }` as `vim.lsp.start` probably attaches to the current buffer

ive also noticed a separate issue where this plugin doesnt seem to disable lsps in other tabs through normal usage (not racing). ie you timeout on one tab, refocus (it'll say Lsp inactive in statusline) then switch to another tab before the start duration, then the lsp is still running.

is the plugin supposed to work as a global stop all lsps, or work per buffer?

**Comment by hinell** [comment]
Please, make a screenshot of two files and use `:LspInfo` command to show which lsps are running and which aren't.

Once again, read [troubleshooting](https://github.com/hinell/lsp-timeout.nvim/blob/main/doc/index.md#troubleshooting) doc subsection on `nvim-navic`

`lsp-timeout` doesn't care about current buffer. It keeps track of lsp per every buffer's window and stop/restart them accordingly per the same buffer every time, regardless of the currently focused one.

**Comment by dylan-chong** [comment]
file a

![image](https://github.com/hinell/lsp-timeout.nvim/assets/17482349/4024c061-86b2-4910-81bd-fbc0ccc3a23a)


file b
![image](https://github.com/hinell/lsp-timeout.nvim/assets/17482349/df214f4c-ecd3-4a20-bc0a-324d882e2559)

ah so you have to be really quick on step 5 (switching to file a)
it may help to try a startTimeout of 0.4 in case you are not fast enough at switching buffers

**Comment by hinell** [comment]
> _Running in single file mode_

This is not expected. You have to deal with this problem first. Checkout `single_file_support` setting for `lspconfig` plugin first. Try also to stop and start LSP clients manually by using `LspStart` / `LspStop` to see if lsps are working directory-relative.

**Comment by dylan-chong** [comment]
Ah okay that's interesting.
In the case shown above, lua_ls and json_lsp have no marker to detect the root of the project.  This makes sense for neovim configs or some random json file.
So running in single file mode is by design

**Comment by hinell** [comment]
@dylan-chong Don't forget to tell whether it helped to solve the issue or not.

**Comment by dylan-chong** [comment]
oh yeah, switching to a project that doesn't single file mode seemed to fix the problem.

interestingly in a monorepo tsserver likes to use single file mode for a defocussed buffer that is in a different subproject to the one currently focussed, then switches back to normal mode when you focus the buffer. but that's a different issue (although probably the one that is causing me to experience the issues in practice)

**Comment by hinell** [comment]
Glad to hear that. Closing for now.

**Comment by hinell** [comment]
Glad to hear that. Closing for now.
