### ISSUE TITLE
attempt to call field 'get_clients' (a nil value)

### ISSUE THREAD

**Issue by BrunoKrugel** [hinell/lsp-timeout.nvim#4]
### Summary

```lua
Error  15:39:31 msg_show.lua_error Error detected while processing FocusLost Autocommands for "*":
15:39:31 msg_show Error executing lua callback: .../share/nvim/lazy/lsp-timeout.nvim/plugin/lsp-timeout.lua:82: attempt to call field 'get_clients' (a nil value)
stack traceback:
	.../share/nvim/lazy/lsp-timeout.nvim/plugin/lsp-timeout.lua:82: in function <.../share/nvim/lazy/lsp-timeout.nvim/plugin/lsp-timeout.lua:72>
```

### Setup

```lua
    {
	"hinell/lsp-timeout.nvim",
	dependencies={ "neovim/nvim-lspconfig" }
    }
```

**Comment by hinell** [comment]
Versions?

**Comment by hinell** [comment]
Please update plugin. Specify nvim version, not the way you setup it.

**Comment by hinell** [comment]
Please update plugin by using git manually:
```sh
cd ~/.local/share/nvim/site/pack/packer/start/lsp-timeout.nvim
git pull --no-tags origin main
```


Specify nvim version, not the way you setup it.

**Comment by DarkKronicle** [comment]
I have the same issue. After installing it (and ensuring I have the latest commit as the version), opening up a lua file, then refocusing, I get the error mentioned above.

neovim version:
```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1692716794
```

**Comment by BrunoKrugel** [comment]
> Please update plugin by using git manually:
> 
> ```sh
> 
> cd ~/.local/share/nvim/site/pack/packer/start/lsp-timeout.nvim
> 
> git pull --no-tags origin main
> 
> ```
> 
> 
> 
> 
> 
> Specify nvim version, not the way you setup it. 
> 
> 
> 
> 
> 
> 

As you can see from the example, I use lazy.nvim, not packer and the plugin is updated.

I am using the stable version.

If you want the version to be specified in the plugin, then you have to change your template for issues, because the template ask for setup, not for the version.

**Comment by hinell** [comment]
>If you want the version to be specified in the plugin, then you have to change your template for issues, because the template ask for setup, not for the version.
It's specifically asking for version in placeholder..., run `nvim --version` and paste it into the field.

**Comment by hinell** [comment]
Sorry for a silly mistake. Should be fixed now. Try to update plugin again adn reopen the ISSUE if it fails.

**Comment by BrunoKrugel** [comment]
> > If you want the version to be specified in the plugin, then you have to change your template for issues, because the template ask for setup, not for the version.
> 
> It's specifically asking for version in placeholder..., run `nvim --version` and paste it into the field.

no, it was not, you changed the placeholder from SETUP to VERSIONS in your last [commit](https://github.com/hinell/lsp-timeout.nvim/commit/e43bae7fff487c036f32ad37485a1d725d6ba6be) 

But the issue is fixed now, thanks anyway.

**Comment by hinell** [comment]
> _` platform, system version, tools version...`_

@BrunoKrugel The above was the previous version of the **Setup** placeholder.
Next time, when filling an issue, specify `nvim` version & plugin version/commit hash.
