### ISSUE TITLE
null-ls sources don't reload after restoring lsp clients

### ISSUE THREAD

**Issue by Zeioth** [hinell/lsp-timeout.nvim#7]
### Summary

This is my `:NullLsInfo` when I open my file (it's loading `beautysh`).

![screenshot_2023-10-16_05-22-47_969674073](https://github.com/hinell/lsp-timeout.nvim/assets/3357792/0bd81cf7-43f6-4735-b751-80f8142f8d8a)

And this is the same `lsp-timeout` reload the clients (it doesn't load it anymore)
![screenshot_2023-10-16_05-22-28_698973754](https://github.com/hinell/lsp-timeout.nvim/assets/3357792/6505bf78-06ee-41e7-9552-cbc48146a3ca)

Just to clarify, null-ls itself works fine (for example, on C, it will work correctly after restoring lsp-timeout because it don't require sources).

If you could try to reproduce, I would be thankful.

### Steps to reproduce

* Install [NormalNvim](https://github.com/NormalNvim/NormalNvim) and the [Mason packages](https://github.com/NormalNvim/NormalNvim/wiki/dependencies#mason-packages)
* Open a bash file and wait until lsp-timeout `startTimeout` kicks in.

When restoring, you should be able to reproduce.

### Versions

* "lsp-timeout.nvim", version = "1.0.1"
* "nvimtools/none-ls.nvim", commit = "f39f627bbdfb33cc4ae4a95b4708e7dba7b9aafc"
* "jay-babu/mason-null-ls.nvim", version = "^2"

**Comment by Zeioth** [comment]
## Easier way to reproduce
* Having at least one external source installed (any null-ls package that is not builtin)
* `:LspStop` and then `:LspStart` → The source will fail to re-start

Maybe null-ls times out? When I do `:LspRestart`, I don't experience this bug.

**Comment by Zeioth** [comment]
It seems running `:lua require("null-ls").toggle({})` after `:LspStart` fixes the issue. I'm gonna keep testing.

**Comment by hinell** [comment]
Anticipated per [troubleshooting](https://github.com/hinell/lsp-timeout.nvim#troubleshooting).

The [null-ls got archived](https://github.com/jose-elias-alvarez/null-ls.nvim) (as of Aug 12, 2023) so you are better to look for [alternatives](https://github.com/jose-elias-alvarez/null-ls.nvim#alternatives) like [efm-langserver](https://github.com/mattn/efm-langserver)

Plugins requiring active LSP may fail or misbehave if they fail to hook into LSP events: `LspAttach` or `LspDetach`; It seems like `nul-ls` fails to do so.

### Workaround
> _It seems manually running `:lua require("null-ls").enable({})`_

I suggets to create an autocmd for that as a workaround and tell me whether it works or not:

```lua
    vim.api.nvim_create_autocmd("LspAttach", {
      callback = function(args)
           require("null-ls").enable({})
    })
```

I would strongly suggest to drop `null-ls`.

**Comment by Zeioth** [comment]
Cool I was writing it. We reached the solution at the same time. 

```
      vim.api.nvim_create_autocmd({ "LspAttach" }, {
        desc = "Start null-ls when starting a lsp client",
        callback = function()
          pcall(function() require("null-ls").enable({}) end)
        end,
      })
```

Ok with that I can fix it on [NormalNvim](https://github.com/NormalNvim/NormalNvim). If you don't want to PR the change, at least would maybe be nice adding it to the readme, because it's a issue many people will propably find.

I use none-ls for now, but I'm secretly rooting for efm-langserver. I think it is a better approach.

**Comment by hinell** [comment]
Reflected in docs:

https://github.com/hinell/lsp-timeout.nvim/blob/main/doc/index.md#troubleshooting
