### ISSUE TITLE
New bug report

### ISSUE THREAD

**Issue by tannerellen** [hinell/lsp-timeout.nvim#8]
### Summary

On neovim 0.94 I am getting an error message that comes up any time my neovim window loses focus:

Error detected while processing FocusLost Autocommands for "*":                                                                                                 
Error executing lua callback: .../share/nvim/lazy/lsp-timeout.nvim/plugin/lsp-timeout.lua:83: attempt to call field 'get_clients' (a nil value)
stack traceback:
        .../share/nvim/lazy/lsp-timeout.nvim/plugin/lsp-timeout.lua:83: in function <.../share/nvim/lazy/lsp-timeout.nvim/plugin/lsp-timeout.lua:72>

I'm loading lsp-timeout with lazy and this error comes up as soon as I switch away from my terminal.

### Steps to reproduce

Launch neovim in terminal, open a file (or don't), then switch to another app.

### Versions

Neovim 0.94

**Comment by hinell** [comment]
@tannerellen Please update to v1.0.2

**Comment by tannerellen** [comment]
Updating to v1.0.2 did the trick. Thanks for the fix!
